# Generated by Django 5.1.4 on 2026-07-17 04:58

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_loads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('invite_code', models.CharField(default=core.models.generate_invite_code, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('expirada', 'Expirada')], default='pendiente', max_length=10)),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_km', models.PositiveIntegerField()),
                ('period_end_km', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unassigned_km', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_load', models.OneToOneField(help_text='Cada carga dispara exactamente una liquidación', on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='core.fuelload')),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_km', models.PositiveIntegerField(help_text='Km que esa persona realmente cargó')),
                ('unassigned_km_share', models.PositiveIntegerField(default=0, help_text='Porción de km sin asignar repartida equitativamente')),
                ('km_driven', models.PositiveIntegerField(editable=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.settlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fuel_type', models.CharField(blank=True, choices=[('nafta', 'Nafta'), ('diesel', 'Diésel'), ('gnc', 'GNC'), ('electrico', 'Eléctrico')], max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('current_km', models.PositiveIntegerField(default=0, help_text='Cache del último km conocido, base para el atajo de 3 dígitos')),
                ('split_unassigned_km_all_members', models.BooleanField(default=True, help_text='True = reparte los km sin asignar entre todos los miembros activos. False = solo entre quienes registraron km en ese período.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.group')),
            ],
        ),
        migrations.AddField(
            model_name='settlement',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='fuelload',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_loads', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False = removido del grupo, se conserva para trazabilidad')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='unique_group_user')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('start_km', models.PositiveIntegerField()),
                ('end_km', models.PositiveIntegerField()),
                ('km_traveled', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_edited', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, help_text='Null hasta que se liquide el período al que pertenece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.settlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'trip_date'], name='core_trip_vehicle_d25995_idx'), models.Index(fields=['vehicle', 'start_km', 'end_km'], name='core_trip_vehicle_e516bf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fuelload',
            index=models.Index(fields=['vehicle', 'load_date'], name='core_fuello_vehicle_90c032_idx'),
        ),
    ]
