# Generated by Django 5.1.4 on 2026-07-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementdetail',
            name='km_driven',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='registered_km + unassigned_km_share, usado para el %. Lo calcula core/services.py', max_digits=8),
        ),
        migrations.AlterField(
            model_name='settlementdetail',
            name='unassigned_km_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porción de km sin asignar repartida equitativamente (puede tener decimales)', max_digits=8),
        ),
    ]
