# Generated by Django 5.1.4 on 2026-09-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_settlementdetail_km_driven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
