# Generated by Django 5.1.4 on 2026-09-09 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehicle_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['vehicle', 'period_start_km', 'period_end_km'], name='settlement_vehicle_km_idx'),
        ),
    ]
